### PR TITLE
Fixing #76

### LINKED ISSUE #76: ManyTables SQL injection
Table names cannot be treated as parameters in the creation of the SQL queries. Therefore, normal C# string formatting is currently used to insert ICAO codes as table names in the ManyTables datastore. Problem is there is an airport with the code "LIKE" - this makes the datastore crash. There may be more datastores with codes that overlap SQL keywords. Might just be fixable with quotation marks?

### PR DESCRIPTION
**Pull request by SebMon**
Closes #76

### CODE REVIEW

File: EventDataStores/ManyTablesPostgreSQLDataStore/ManyTablesPostgreSQLDatastore.cs [hunk 1]
```diff
@@ -85,7 +85,7 @@ public async Task AddOrUpdateFlightAsync(Flight flight)
 
                 string createTableSql =
                     $"""
-                     CREATE TABLE {airport} (
+                     CREATE TABLE "{airport}_table" (
```
Comment (AlexanderNorup) [inline EventDataStores/ManyTablesPostgreSQLDataStore/ManyTablesPostgreSQLDatastore.cs:88]: This will work, but still isn't safe. 
If an airport's ICAO is `hello"`, you  can still escape. But we don't have any airports like that and this isn't used "for real" so it's fine for our testing.

**Review by IsabellaNorup — APPROVED** [review]

File: EventDataStores/ManyTablesPostgreSQLDataStore/ManyTablesPostgreSQLDatastore.cs (hunk 1 above)
Comment (SebMon) [reply EventDataStores/ManyTablesPostgreSQLDataStore/ManyTablesPostgreSQLDatastore.cs]: I have now added some sanitation of airport codes just for good measure
